export const languages = {
  english: {
    on_board_one: {
      title: 'Skol Experience',
      description:
        'We provide refreshing choices to thirsty Rwandan beer lovers by placing the consumers at the heart of everything we do',
    },
    on_board_two: {
      title: 'Win gifts and prizes',
      description:
        'Unlock amazing gifts and prizes through our loyalty program',
    },
    on_board_three: {
      title: 'Get Insights',
      description:
        'Unlock the power of your data and get the insights you need.',
    },

    enter_phone_number_title: 'Enter Phone Number',
    enter_phone_number_description:
      "You'll received a 6 digits code to verify next",
    getting_started: 'Getting Started',
    next: 'Next',
    phone_number: 'Enter Phone number',
    phone_required: 'Phone number is required',
    invalid_phone: 'Invalid phone number',
    otp_required: 'OTP code is required',
    invalid_otp: 'Invalid OTP code',
    sent_otp: 'Enter OTP code sent you to ',
    enter_otp_code: 'Verify OTP Code',
    otp_code: 'OTP Code (6 Digits)',
    submit: 'Submit',
    surveys: 'Surveys',
    all_surveys: 'All Surveys',
    available_surveys: 'Available Surveys',
    progress_surveys: 'Progress Surveys',
    completed_surveys: 'Completed Surveys',
    rewards: 'Zawadi',
    profile_txt: 'Profile',
    new_survey: 'Survey Form',
    survey_title_label: 'Survey Title',
    survey_title_placeholder: 'Enter Title',
    field_with_star_required: 'Fields with (*) are required',
    save_as_draft: 'Save as Draft',
    survey_description_placeholder: 'Enter Description',
    survey_description_label: 'Survey Description',
    save: 'Save',
    question_txt: 'Question',
    enter_question: 'Enter Question',
    enter_answer: 'Enter Answer',
    phone_auth_failed: 'Phone auth failed, please try again',
    wrong_otp_code: 'Wrong OTP code',
    resend_otp: 'Resend OTP',
    sent_otp_success: 'OTP has been sent successful to',
    survey_title_required: 'Survey title is required',
    preview: 'Preview',
    survey_added_failed:
      'Add survey has been failed,check the errors and try again',
    survey_added_success: 'New survey added successfully',
    enter_option: 'Enter option',
    question_added_success: 'Question has been added successful',
    question_added_failed:
      'No question added please check your internet and try again',
    no_survey_title: 'No Survey',
    no_survey_description:
      'Surveys will be listed here, please come back later',
    new_question: 'Question Form',
    edit_txt: 'Edit',
    delete_txt: 'Delete',
    delete_survey: 'Are you sure, want to delete this survey',
    NO: 'NO',
    YES: 'YES',
    delete_survey_desc: 'Survey will be delete permenently, there is no undo',
    rewards: 'Rewards',
    your_balance: 'Your Balance',
    points: 'Point(s)',
    available_points: 'Available points to convert',
    convert: 'Convert',
    my_account: 'Profile',
    ask_location_title: 'Allow location access',
    ask_location_description:
      'Before we start we need to access your location, so we can track your activities while you are using this app. is that okay with you?',
    settings: 'Settings',
    language_text: 'Default Language',
    logout: 'Logout',
    complete_profile: 'Complete Profile',
    welcome_missing_profile_info_title: 'Welcome to SKOLé',
    welcome_missing_profile_info_description:
      'Your name is missing please update your profile',
    my_account_text: 'My Account',
    change_profile_picture: 'Change profile',
    fullname: 'Fullname',
    email_address: 'Email Address',
    update_profile: 'Update Profile',
    phone_txt: 'Phone Number',
    name_is_required: 'Name is required',
    invalid_email: 'Invalid email address',
    user_update_success: 'User updated successful',
    user_update_failed:
      'Something went wrong, please check your internet and try again',
    home: 'Home',
    dashboard: 'Dashboard',
    email_required: 'Email is required',
    invalid_email: 'Invalid email address',
    age_required: 'Age is required',
    gender_required: 'Gender is required',
    age_txt: 'Age',
    email_txt: 'Email Address',
    complete_profile: 'Complete your Profile',
    email_address_placeholder: 'eg:jhondoe@example.com',
    gender_txt: 'Gender',
    male: 'Male',
    female: 'Female',
    where_live: 'Where do you live?',
    firstname_is_required: 'Firstname is required',
    lastname_is_required: 'lastname is required',
    lastname_placeholder: 'Enter your lastname',
    firstname_placeholder: 'Enter your firstname',
    firstname_txt: 'Firstname',
    lastname_txt: 'Lastname',
    almost_there: 'Almost there',
    province_txt: 'Province',
    district_txt: 'District',
    cell_txt: 'Cell',
    sector_txt: 'Sector',
    village_txt: 'Village',
    select_province_txt: 'Select province',
    select_district_txt: 'Select district',
    select_cell_txt: 'Select cell',
    select_sector_txt: 'Select sector',
    select_village_txt: 'Select village',
    skip: 'Skip',
    search_text: 'Search...',
    total_points: 'Points',
    survey_introduction_label: 'Survey Introduction',
    survey_introduction_placeholder: 'Introduction',
    introduction_explain:
      'This introduction is for the surveyor to guide them how they will introduce themselves: you can include dynamic data eg: {firstname} {lastname} {sector} {cell} {village} ',
  },
};
